---
name: approval_rules_disable_joins
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136588
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431564
milestone: '16.7'
type: development
group: group::source code
default_enabled: false
