---
name: ci_process_catalog_resource_sync_events
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137238
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/432963
milestone: '16.7'
type: development
group: group::pipeline authoring
default_enabled: false
