---
name: contributions_calendar_refactoring
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/134991
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429648
milestone: '16.6'
type: development
group: group::tenant scale
default_enabled: false
