---
name: create_user_ns_outside_model
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136402
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431542
milestone: '16.7'
type: development
group: group::tenant scale
default_enabled: false
