---
name: custom_job_waiter_ttl
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130140
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/423794
milestone: '16.4'
type: development
group: group::import and integrate
default_enabled: false
