---
name: exact_matches_first_group_transfer
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130773
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424242
milestone: '16.4'
type: development
group: group::project management
default_enabled: false
