---
name: group_users_autocomplete_using_batch_reduction
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/134915
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/430268
milestone: '16.7'
type: development
group: group::tenant scale
default_enabled: false
