---
name: hide_snippets_of_banned_users
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131725
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425391
milestone: '16.5'
type: development
group: group::anti-abuse
default_enabled: false
