---
name: npm_optimize_metadata_generation
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/128514
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/416346
milestone: '16.4'
type: development
group: group::package registry
default_enabled: false
