---
name: renaming_project_with_tags
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/135422
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429734
milestone: '16.7'
type: development
group: group::container registry
default_enabled: false
