---
name: saml_microsoft_attribute_names
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136734
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/430348
milestone: '16.7'
type: development
group: group::authentication
default_enabled: false
