---
name: user_pat_rest_api
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/131923
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425967
milestone: '16.5'
type: development
group: group::authentication and authorization
default_enabled: false
