---
name: wiki_redirection
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/150727
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/460097
milestone: '17.0'
type: development
group: group::knowledge
default_enabled: false
