---
name: write_project_authorizations_is_unique
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130299
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424097
milestone: '16.4'
type: development
group: group::security policies
default_enabled: false
