---
name: ci_atomic_processing_ordered_update_stage
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/450395
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/147875
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/451992
milestone: '16.11'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
