---
name: ci_create_partitions_102
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/148376
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/454519
milestone: '16.11'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
