---
name: ci_refactor_has_ci_config_file
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/26169
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141990
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17406
milestone: '16.9'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
