---
name: ci_send_tag_list_for_external_validation
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/335904
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/147460
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/369876
milestone: '16.11'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
