---
name: create_user_details_with_user_creation
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/461656
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/152995
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/461674
milestone: '17.1'
group: group::acquisition
type: gitlab_com_derisk
default_enabled: false
