---
name: deprecate_unified_approval_rules
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/388191
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/150182
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/457258
milestone: '17.0'
group: group::environments
type: gitlab_com_derisk
default_enabled: false
