---
name: do_not_use_exclusive_lease_for_user_activity_service
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/441536
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/151342
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/458719
milestone: '17.0'
group: group::tenant scale
type: gitlab_com_derisk
default_enabled: false
