---
name: native_header_anchors
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/440733
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/144690
rollout_issue_url:
milestone: '17.0'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
