---
name: skip_copy_operation_in_generic_packages_upload
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429060
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/147454
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/450992
milestone: '16.11'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
