---
name: track_ci_pipeline_created_event
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429065
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142356
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17445
milestone: '16.9'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
