---
name: update_default_organization_users
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/437891
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141500
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/437896
milestone: '16.9'
group: group::tenant scale
type: gitlab_com_derisk
default_enabled: false
