---
name: use_ids_for_markdown_upload_urls
feature_issue_url: https://gitlab.com/gitlab-sirt/shared-incidents/incident_5281/-/work_items/6
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/150939
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/461757
milestone: '17.0'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
