
---
name: use_primary_for_update_computations
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/416207
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/145792
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/443293
milestone: '16.10'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
