---
name: workhorse_google_client
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/9457
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/96891
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/372596
milestone: '15.6'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
