---
description: User clicks "merge requests assigned to me"
internal_events: true
action: click_merge_requests_assigned_to_me_in_command_palette
identifiers:
- namespace
- user
product_section: core_platform
product_stage: data_stores
product_group: global_search
milestone: '17.1'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/147919
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
