---
name: google_cloud_runner_provisioning
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/437901
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141521
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/441627
milestone: '16.10'
group: group::runner
type: beta
default_enabled: false
