---
name: prevent_issue_epic_search
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/457756
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/153668
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/463698
milestone: '17.1'
group: group::duo chat
type: beta
default_enabled: false
