---
key_path: counts_weekly.aggregated_metrics.xmau_project_management
description: Unique users interacting with Project Management features
product_section: dev
product_stage: plan
product_group: project_management
value_type: number
status: active
milestone: '14.9'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/81336
time_frame: 7d
instrumentation_class: RedisHLLMetric
data_source: redis_hll
events:
- name: users_creating_work_items
  unique: user.id
- name: users_updating_work_item_title
  unique: user.id
- name: users_updating_work_item_dates
  unique: user.id
- name: users_updating_work_item_labels
  unique: user.id
- name: users_updating_work_item_iteration
  unique: user.id
- name: users_updating_weight_estimate
  unique: user.id
- name: users_updating_work_item_milestone
  unique: user.id
- name: users_updating_work_item_todo
  unique: user.id
data_category: optional
distribution:
- ce
- ee
tier:
- free
- premium
- ultimate
