pre-merge-checks:
  extends:
    - .pre-merge:rules:pre-merge-checks
    - .fast-no-clone-job
  variables:
    # We use > instead of | because we want the files to be space-separated.
    FILES_TO_DOWNLOAD: >
      scripts/utils.sh
      scripts/pipeline/merge-train-checks.rb
  image: ${GITLAB_DEPENDENCY_PROXY_ADDRESS}ruby:${RUBY_VERSION}-alpine3.16
  stage: pre-merge
  script:
    - install_gitlab_gem
    - chmod u+x scripts/pipeline/merge-train-checks.rb && scripts/pipeline/merge-train-checks.rb
